//! ABR Decision Engine calculating target bitrates per RFC-0002 §14.2.
//!
//! # Delay, not just loss
//!
//! The engine used to react to packet loss alone. On the paths Renderd actually
//! runs over — home routers and Wi-Fi radios that queue rather than drop — loss
//! is the *last* thing to show up: first the queue fills, every frame arrives
//! later than the one before, and only once the buffer overflows does anything
//! get dropped. By then the viewer is seconds behind. With BBR pacing on the
//! host the excess is held even longer, in the sender's own queue, where the
//! network never sees it and never drops it.
//!
//! So the engine now takes [`Signals`]: loss, the viewer's measured one-way
//! queuing delay, the host's own send-queue depth, and the viewer's receive
//! rate. Growing delay backs the bitrate off long before any loss, toward what
//! the viewer is actually receiving; the bitrate only probes upward while delay
//! is low *and* the encoder is actually using what it already has.

use renderd_proto::types::BitrateKbps;

use crate::state::AbrState;

/// Queuing delay above which the engine backs off.
pub const DELAY_BACKOFF_MS: f64 = 60.0;

/// Queuing delay above which the engine halves the bitrate outright.
pub const DELAY_PANIC_MS: f64 = 250.0;

/// Queuing delay below which the link counts as clean for probing.
pub const DELAY_CLEAN_MS: f64 = 20.0;

/// Multiplicative decrease applied on each backoff.
const BACKOFF_FACTOR: f64 = 0.85;

/// Fraction of the measured receive rate a backoff will not go above.
const BACKOFF_RECEIVE_RATE_FRACTION: f64 = 0.95;

/// Fraction of the measured receive rate a panic will not go above.
const PANIC_RECEIVE_RATE_FRACTION: f64 = 0.7;

/// Relative increase per probe, bounded above by the configured step.
const PROBE_FACTOR: f64 = 0.08;

/// Reports to wait after a backoff before backing off again.
///
/// A queue takes time to drain even after the encoder slows down; cutting again
/// on every report while it does would overshoot far below the link rate.
const BACKOFF_HOLD_TICKS: usize = 3;

/// Everything the engine reacts to, from one feedback report.
#[derive(Debug, Clone, Copy, PartialEq, Default)]
pub struct Signals {
    /// Fraction of frames lost over the report interval, 0.0 to 1.0.
    pub loss_rate: f64,
    /// One-way queuing delay the viewer measured, in milliseconds. 0 if unknown.
    pub queue_delay_ms: f64,
    /// Time the host's own send queue needs to drain, in milliseconds.
    pub send_queue_ms: f64,
    /// Video the viewer received over the report interval, in kbps. 0 if unknown.
    pub receive_rate_kbps: f64,
    /// The encoder produced well under its target (a still desktop), so a clean
    /// link says nothing about whether a higher bitrate would fit.
    pub app_limited: bool,
}

impl Signals {
    /// Signals carrying only a loss rate, as from a peer that reports nothing else.
    #[must_use]
    pub const fn from_loss(loss_rate: f64) -> Self {
        Self {
            loss_rate,
            queue_delay_ms: 0.0,
            send_queue_ms: 0.0,
            receive_rate_kbps: 0.0,
            app_limited: false,
        }
    }

    /// The larger of the viewer-measured and host-measured queuing delay.
    #[must_use]
    pub fn congestion_delay_ms(&self) -> f64 {
        self.queue_delay_ms.max(self.send_queue_ms).max(0.0)
    }
}

/// Output decision generated by the ABR decision engine.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BitrateDecision {
    /// Current operational ABR state.
    pub state: AbrState,
    /// Calculated target bitrate in Kbps.
    pub target_bitrate_kbps: BitrateKbps,
    /// Indicates whether an IDR keyframe request should be issued immediately.
    pub request_keyframe: bool,
}

/// ABR Decision Engine driving dynamic encoder bitrate adjustments.
#[derive(Debug, Clone)]
pub struct AbrEngine {
    min_bitrate: BitrateKbps,
    max_bitrate: BitrateKbps,
    current_bitrate: BitrateKbps,
    step: BitrateKbps,
    loss_threshold: f64,
    panic_threshold: f64,
    state: AbrState,
    consecutive_clean_intervals: usize,
    probe_trigger_intervals: usize,
    backoff_hold: usize,
}

impl AbrEngine {
    /// Creates a new `AbrEngine` initialized with parameter bounds.
    ///
    /// `step` is the largest single increase a probe may make; probes otherwise
    /// grow the bitrate by 8%, so they stay proportionate on a slow link.
    #[must_use]
    pub const fn new(
        min_bitrate: BitrateKbps,
        max_bitrate: BitrateKbps,
        initial_bitrate: BitrateKbps,
        step: BitrateKbps,
        loss_threshold: f64,
        panic_threshold: f64,
    ) -> Self {
        Self {
            min_bitrate,
            max_bitrate,
            current_bitrate: initial_bitrate,
            step,
            loss_threshold,
            panic_threshold,
            state: AbrState::Steady,
            consecutive_clean_intervals: 0,
            probe_trigger_intervals: 5,
            backoff_hold: 0,
        }
    }

    /// Returns the currently calculated target bitrate in Kbps.
    #[must_use]
    pub const fn current_bitrate(&self) -> BitrateKbps {
        self.current_bitrate
    }

    /// Returns the current ABR state.
    #[must_use]
    pub const fn state(&self) -> AbrState {
        self.state
    }

    /// Evaluates a loss rate alone. Equivalent to [`Self::update_signals`] with
    /// [`Signals::from_loss`].
    pub fn update(&mut self, loss_rate: f64) -> BitrateDecision {
        self.update_signals(&Signals::from_loss(loss_rate))
    }

    /// Evaluates one feedback report and returns the next bitrate decision.
    pub fn update_signals(&mut self, signals: &Signals) -> BitrateDecision {
        let loss = signals.loss_rate.clamp(0.0, 1.0);
        let delay = signals.congestion_delay_ms();
        let next_state = AbrState::classify(
            loss,
            delay,
            self.loss_threshold,
            self.panic_threshold,
            self.consecutive_clean_intervals,
            self.probe_trigger_intervals,
        );
        self.backoff_hold = self.backoff_hold.saturating_sub(1);

        let mut request_keyframe = false;
        match next_state {
            AbrState::Steady => {
                if loss <= self.loss_threshold && delay < DELAY_CLEAN_MS {
                    self.consecutive_clean_intervals += 1;
                } else {
                    self.consecutive_clean_intervals = 0;
                }
            }
            AbrState::ProbeUp => {
                self.consecutive_clean_intervals = 0;
                if !signals.app_limited {
                    self.probe_up();
                }
            }
            AbrState::Backoff => {
                self.consecutive_clean_intervals = 0;
                if self.backoff_hold == 0 {
                    self.back_off(signals.receive_rate_kbps);
                    self.backoff_hold = BACKOFF_HOLD_TICKS;
                }
            }
            AbrState::Panic => {
                self.consecutive_clean_intervals = 0;
                // Halve once per panic episode, not on every report inside it:
                // the queue that caused it needs a moment to drain.
                if self.state != AbrState::Panic {
                    self.panic(signals.receive_rate_kbps);
                    self.backoff_hold = BACKOFF_HOLD_TICKS;
                }
                // A keyframe only helps when frames were actually lost. Forcing one
                // on entering Panic because of *delay* would inject the largest,
                // least compressible frame into a link that is already queuing.
                // And even for loss, one per episode: `classify` is level-triggered,
                // so sustained loss re-enters Panic every report.
                request_keyframe = self.state != AbrState::Panic && loss >= self.panic_threshold;
            }
        }

        self.state = next_state;

        BitrateDecision {
            state: self.state,
            target_bitrate_kbps: self.current_bitrate,
            request_keyframe,
        }
    }

    fn probe_up(&mut self) {
        let current = f64::from(self.current_bitrate.0);
        let proportional = (current * PROBE_FACTOR).max(100.0);
        let increase = proportional.min(f64::from(self.step.0.max(1)));
        self.set_bitrate(current + increase);
    }

    fn back_off(&mut self, receive_rate_kbps: f64) {
        let mut next = f64::from(self.current_bitrate.0) * BACKOFF_FACTOR;
        if receive_rate_kbps > 0.0 {
            // Queuing means the path is the bottleneck, so what the viewer is
            // receiving right now is the best estimate of what it can carry.
            next = next.min(receive_rate_kbps * BACKOFF_RECEIVE_RATE_FRACTION);
        }
        self.set_bitrate(next);
    }

    fn panic(&mut self, receive_rate_kbps: f64) {
        let mut next = f64::from(self.current_bitrate.0) / 2.0;
        if receive_rate_kbps > 0.0 {
            next = next.min(receive_rate_kbps * PANIC_RECEIVE_RATE_FRACTION);
        }
        self.set_bitrate(next);
    }

    #[allow(clippy::cast_possible_truncation, clippy::cast_sign_loss)]
    fn set_bitrate(&mut self, kbps: f64) {
        let clamped = kbps.clamp(
            f64::from(self.min_bitrate.0),
            f64::from(self.max_bitrate.0.max(self.min_bitrate.0)),
        );
        self.current_bitrate = BitrateKbps(clamped.round() as u32);
    }
}

#[cfg(test)]
mod tests {

    use super::*;

    fn engine(initial: u32) -> AbrEngine {
        AbrEngine::new(
            BitrateKbps(1_500),
            BitrateKbps(10_000),
            BitrateKbps(initial),
            BitrateKbps(1_000),
            0.02,
            0.15,
        )
    }

    fn delay(ms: f64) -> Signals {
        Signals {
            queue_delay_ms: ms,
            ..Signals::default()
        }
    }

    #[test]
    fn test_abr_engine_probe_up() {
        let mut engine = AbrEngine::new(
            BitrateKbps(5000),
            BitrateKbps(50000),
            BitrateKbps(10000),
            BitrateKbps(2000),
            0.02,
            0.10,
        );

        for _ in 0..5 {
            let decision = engine.update(0.0);
            assert_eq!(decision.state, AbrState::Steady);
            assert_eq!(decision.target_bitrate_kbps, BitrateKbps(10000));
        }

        // 6th clean interval triggers ProbeUp by 8%, within the 2000 kbps step.
        let decision = engine.update(0.0);
        assert_eq!(decision.state, AbrState::ProbeUp);
        assert_eq!(decision.target_bitrate_kbps, BitrateKbps(10800));
    }

    /// Sustained loss must force exactly one keyframe on entering Panic, not one
    /// per tick — a keyframe storm on an already-congested link only feeds the
    /// loss that triggered it (see engine.rs `update` doc comment).
    #[test]
    fn test_panic_forces_keyframe_only_on_entry_not_every_tick() {
        let mut engine = AbrEngine::new(
            BitrateKbps(5000),
            BitrateKbps(50000),
            BitrateKbps(20000),
            BitrateKbps(2000),
            0.02,
            0.10,
        );

        let entering = engine.update(0.50);
        assert_eq!(entering.state, AbrState::Panic);
        assert!(entering.request_keyframe);

        for _ in 0..10 {
            let still_panicking = engine.update(0.50);
            assert_eq!(still_panicking.state, AbrState::Panic);
            assert!(
                !still_panicking.request_keyframe,
                "must not re-request a keyframe while still in Panic"
            );
        }

        // Recovering out of Panic and panicking again must force a fresh keyframe.
        let recovered = engine.update(0.0);
        assert_ne!(recovered.state, AbrState::Panic);

        let re_entering = engine.update(0.50);
        assert_eq!(re_entering.state, AbrState::Panic);
        assert!(re_entering.request_keyframe);
    }

    /// The whole point: a queue building with zero loss must pull the bitrate
    /// down, toward what the viewer is actually receiving.
    #[test]
    fn test_rising_delay_backs_off_without_any_loss() {
        let mut engine = engine(10_000);
        let decision = engine.update_signals(&Signals {
            queue_delay_ms: 80.0,
            receive_rate_kbps: 6_000.0,
            ..Signals::default()
        });
        assert_eq!(decision.state, AbrState::Backoff);
        assert_eq!(decision.target_bitrate_kbps, BitrateKbps(5_700));
        assert!(!decision.request_keyframe);
    }

    #[test]
    fn test_host_send_queue_counts_as_delay() {
        let mut engine = engine(8_000);
        let decision = engine.update_signals(&Signals {
            send_queue_ms: 100.0,
            ..Signals::default()
        });
        assert_eq!(decision.state, AbrState::Backoff);
        assert_eq!(decision.target_bitrate_kbps, BitrateKbps(6_800));
    }

    /// A queue keeps reading high for a few reports after the cut while it
    /// drains; backing off on every one of them would overshoot far below the
    /// link rate.
    #[test]
    fn test_backoff_holds_while_the_queue_drains() {
        let mut engine = engine(10_000);
        assert_eq!(
            engine.update_signals(&delay(80.0)).target_bitrate_kbps,
            BitrateKbps(8_500)
        );
        for _ in 0..2 {
            assert_eq!(
                engine.update_signals(&delay(80.0)).target_bitrate_kbps,
                BitrateKbps(8_500)
            );
        }
        assert_eq!(
            engine.update_signals(&delay(80.0)).target_bitrate_kbps,
            BitrateKbps(7_225)
        );
    }

    /// Delay-driven panic halves the bitrate but must not ask for a keyframe:
    /// nothing was lost, and an IDR is the worst thing to add to a full queue.
    #[test]
    fn test_delay_panic_halves_without_a_keyframe() {
        let mut engine = engine(10_000);
        let decision = engine.update_signals(&delay(400.0));
        assert_eq!(decision.state, AbrState::Panic);
        assert_eq!(decision.target_bitrate_kbps, BitrateKbps(5_000));
        assert!(!decision.request_keyframe);
        // Staying in Panic does not keep halving.
        let again = engine.update_signals(&delay(400.0));
        assert_eq!(again.target_bitrate_kbps, BitrateKbps(5_000));
    }

    #[test]
    fn test_panic_is_capped_by_receive_rate() {
        let mut engine = engine(10_000);
        let decision = engine.update_signals(&Signals {
            queue_delay_ms: 400.0,
            receive_rate_kbps: 4_000.0,
            ..Signals::default()
        });
        assert_eq!(decision.target_bitrate_kbps, BitrateKbps(2_800));
    }

    /// Moderate delay is neither clean nor congested: hold, and do not count
    /// toward the next probe.
    #[test]
    fn test_moderate_delay_holds_and_resets_probe_counter() {
        let mut engine = engine(5_000);
        for _ in 0..4 {
            engine.update(0.0);
        }
        let decision = engine.update_signals(&delay(40.0));
        assert_eq!(decision.state, AbrState::Steady);
        assert_eq!(decision.target_bitrate_kbps, BitrateKbps(5_000));
        for _ in 0..5 {
            assert_eq!(engine.update(0.0).state, AbrState::Steady);
        }
        assert_eq!(engine.update(0.0).state, AbrState::ProbeUp);
    }

    /// A still desktop sends almost nothing, so a clean link proves nothing
    /// about headroom; probing then would bank a bitrate the path cannot carry
    /// the moment something starts moving.
    #[test]
    fn test_no_probe_while_app_limited() {
        let mut engine = engine(5_000);
        let idle = Signals {
            app_limited: true,
            ..Signals::default()
        };
        for _ in 0..30 {
            assert_eq!(
                engine.update_signals(&idle).target_bitrate_kbps,
                BitrateKbps(5_000)
            );
        }
    }

    #[test]
    fn test_probe_is_proportional_on_a_slow_link() {
        let mut engine = engine(2_000);
        for _ in 0..5 {
            engine.update(0.0);
        }
        // 8% of 2000, not the full 1000 kbps step.
        assert_eq!(engine.update(0.0).target_bitrate_kbps, BitrateKbps(2_160));
    }

    #[test]
    fn test_bitrate_stays_within_bounds() {
        let mut low = engine(1_600);
        for _ in 0..20 {
            let decision = low.update_signals(&delay(500.0));
            assert!(decision.target_bitrate_kbps >= BitrateKbps(1_500));
            low.update(0.0);
        }
        let mut high = engine(9_900);
        for _ in 0..200 {
            assert!(high.update(0.0).target_bitrate_kbps <= BitrateKbps(10_000));
        }
    }
}
