//! ABR Decision Engine calculating target bitrates per RFC-0002 §14.2.

use renderd_proto::types::BitrateKbps;

use crate::state::AbrState;

/// Output decision generated by the ABR decision engine.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct BitrateDecision {
    /// Current operational ABR state.
    pub state: AbrState,
    /// Calculated target bitrate in Kbps.
    pub target_bitrate_kbps: BitrateKbps,
    /// Indicates whether an IDR keyframe request should be issued immediately.
    pub request_keyframe: bool,
}

/// ABR Decision Engine driving dynamic encoder bitrate adjustments.
#[derive(Debug, Clone)]
pub struct AbrEngine {
    min_bitrate: BitrateKbps,
    max_bitrate: BitrateKbps,
    current_bitrate: BitrateKbps,
    step: BitrateKbps,
    loss_threshold: f64,
    panic_threshold: f64,
    state: AbrState,
    consecutive_clean_intervals: usize,
    probe_trigger_intervals: usize,
}

impl AbrEngine {
    /// Creates a new `AbrEngine` initialized with parameter bounds.
    #[must_use]
    pub const fn new(
        min_bitrate: BitrateKbps,
        max_bitrate: BitrateKbps,
        initial_bitrate: BitrateKbps,
        step: BitrateKbps,
        loss_threshold: f64,
        panic_threshold: f64,
    ) -> Self {
        Self {
            min_bitrate,
            max_bitrate,
            current_bitrate: initial_bitrate,
            step,
            loss_threshold,
            panic_threshold,
            state: AbrState::Steady,
            consecutive_clean_intervals: 0,
            probe_trigger_intervals: 5,
        }
    }

    /// Returns the currently calculated target bitrate in Kbps.
    #[must_use]
    pub const fn current_bitrate(&self) -> BitrateKbps {
        self.current_bitrate
    }

    /// Returns the current ABR state.
    #[must_use]
    pub const fn state(&self) -> AbrState {
        self.state
    }

    /// Evaluates current frame loss metrics and calculates next target bitrate decision.
    #[allow(clippy::float_cmp)]
    pub fn update(&mut self, loss_rate: f64) -> BitrateDecision {
        if loss_rate <= self.loss_threshold {
            self.consecutive_clean_intervals += 1;
        } else {
            self.consecutive_clean_intervals = 0;
        }

        let next_state = self.state.next_state(
            loss_rate,
            self.loss_threshold,
            self.panic_threshold,
            self.consecutive_clean_intervals,
            self.probe_trigger_intervals,
        );

        let mut request_keyframe = false;

        match next_state {
            AbrState::Steady => {}
            AbrState::ProbeUp => {
                let next = self.current_bitrate.0.saturating_add(self.step.0);
                self.current_bitrate = BitrateKbps(next.min(self.max_bitrate.0));
                self.consecutive_clean_intervals = 0;
            }
            AbrState::Backoff => {
                let dec = self.step.0.saturating_mul(2);
                let next = self.current_bitrate.0.saturating_sub(dec);
                self.current_bitrate = BitrateKbps(next.max(self.min_bitrate.0));
            }
            AbrState::Panic => {
                let next = self.current_bitrate.0 / 2;
                self.current_bitrate = BitrateKbps(next.max(self.min_bitrate.0));
                // Only force a keyframe on the transition into Panic, not on every
                // tick we remain in it. `next_state` is level-triggered on loss_rate,
                // so sustained loss re-enters Panic every call; forcing a fresh IDR
                // each time injects the largest, least compressible frame the encoder
                // produces into a link that's already congested, which sustains the
                // very loss that triggered it. One keyframe per panic episode is enough
                // to recover from decode desync; requesting another every ~250ms while
                // the first hasn't even finished draining only feeds the feedback loop.
                request_keyframe = self.state != AbrState::Panic;
            }
        }

        self.state = next_state;

        BitrateDecision {
            state: self.state,
            target_bitrate_kbps: self.current_bitrate,
            request_keyframe,
        }
    }
}

#[cfg(test)]
mod tests {

    use super::*;

    #[test]
    fn test_abr_engine_probe_up() {
        let mut engine = AbrEngine::new(
            BitrateKbps(5000),
            BitrateKbps(50000),
            BitrateKbps(10000),
            BitrateKbps(2000),
            0.02,
            0.10,
        );

        for _ in 0..4 {
            let decision = engine.update(0.0);
            assert_eq!(decision.state, AbrState::Steady);
            assert_eq!(decision.target_bitrate_kbps, BitrateKbps(10000));
        }

        // 5th clean interval triggers ProbeUp
        let decision = engine.update(0.0);
        assert_eq!(decision.state, AbrState::ProbeUp);
        assert_eq!(decision.target_bitrate_kbps, BitrateKbps(12000));
    }

    /// Sustained loss must force exactly one keyframe on entering Panic, not one
    /// per tick — a keyframe storm on an already-congested link only feeds the
    /// loss that triggered it (see engine.rs `update` doc comment).
    #[test]
    fn test_panic_forces_keyframe_only_on_entry_not_every_tick() {
        let mut engine = AbrEngine::new(
            BitrateKbps(5000),
            BitrateKbps(50000),
            BitrateKbps(20000),
            BitrateKbps(2000),
            0.02,
            0.10,
        );

        let entering = engine.update(0.50);
        assert_eq!(entering.state, AbrState::Panic);
        assert!(entering.request_keyframe);

        for _ in 0..10 {
            let still_panicking = engine.update(0.50);
            assert_eq!(still_panicking.state, AbrState::Panic);
            assert!(
                !still_panicking.request_keyframe,
                "must not re-request a keyframe while still in Panic"
            );
        }

        // Recovering out of Panic and panicking again must force a fresh keyframe.
        let recovered = engine.update(0.0);
        assert_ne!(recovered.state, AbrState::Panic);

        let re_entering = engine.update(0.50);
        assert_eq!(re_entering.state, AbrState::Panic);
        assert!(re_entering.request_keyframe);
    }
}
