[package]
name        = "renderd-proto"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "`Protobuf` types for Renderd control plane."

[dependencies]
prost = { workspace = true }
uuid  = { workspace = true }

[lints]
workspace = true
