//! Protobuf types and domain newtypes for the Renderd control plane.
//!
//! This crate owns every message type exchanged on QUIC Stream 0, plus strongly-typed
//! newtype wrappers that prevent raw integer mix-ups at compile time.
//!
//! # Architecture
//!
//! The crate is split into four modules:
//!
//! - [`generated`] — prost-generated structs from `proto/renderd.proto` (committed;
//!   regenerated by `tools/proto-gen`).
//! - [`types`] — domain newtypes: [`FrameId`], [`FragmentId`], [`BitrateKbps`],
//!   [`VsyncPeriodNs`], [`ViewerId`], [`HostId`].
//! - [`envelope`] — [`MessageKind`] enum and validation traits ([`ValidateHello`],
//!   [`ValidateConfig`]) for the [`Envelope`] oneof wrapper.
//! - [`error`] — [`ProtoError`] enum covering version incompatibility and field
//!   validation failures.
//!
//! # Usage
//!
//! ```rust
//! use renderd_proto::{Envelope, MessageKind, ValidateHello};
//! use renderd_proto::generated::renderd::SessionHello;
//!
//! // Inspect an envelope received on QUIC Stream 0
//! fn handle_envelope(env: &Envelope) {
//!     match env.kind() {
//!         MessageKind::SessionHello => { /* begin session negotiation */ }
//!         MessageKind::Error        => { /* handle protocol error */ }
//!         _                         => { /* route to appropriate handler */ }
//!     }
//! }
//! ```
//!
//! # Panics
//!
//! This crate does not panic. All fallible operations return [`Result<T, ProtoError>`].

pub mod envelope;
pub mod error;
pub mod generated;
pub mod types;

pub use envelope::*;
pub use error::*;
pub use generated::renderd::*;
pub use types::*;
