[package]
name        = "renderd-discovery"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "mDNS service discovery interface."

[dependencies]
thiserror     = { workspace = true }
uuid          = { workspace = true, features = ["v5"] }
renderd-proto = { workspace = true }
tokio         = { workspace = true }

[target.'cfg(target_os = "macos")'.dependencies]
core-foundation = { workspace = true }

[target.'cfg(target_os = "windows")'.dependencies]
windows = { workspace = true }

[lints.rust]
unsafe_code = "warn"

[lints.clippy]
all                     = { level = "warn", priority = -1 }
pedantic                = { level = "warn", priority = -1 }
nursery                 = { level = "warn", priority = -1 }
module_name_repetitions = "allow"
missing_errors_doc      = "allow"
